

task: detect # (str) YOLO task, i.e. detect, segment, classify, pose
mode: train # (str) YOLO mode, i.e. train, val, predict, export, track, benchmark

# Train settings -------------------------------------------------------------------------------------------------------
model: base # (str, optional) path to model file, i.e. yolov8n.pt, yolov8n.yaml
name: swin_patch4_window7_224 #
data: cifar10 # (str, optional) path to data file, i.e. coco128.yaml
in_chans: 3 #(int) dimension of input
imgsz: 224 # (int | list) input images size as int for train and val modes, or list[w,h] for predict and export modes
labels: 10 # (int) number of labels



# Config model ------------------------------------------------------------------------------------------------------
patches: 4 # (int) patches size
nheads: [3, 6, 12, 24] # (list) number of attention heads
embed_dim: 96 # (int) number of channels 
depths: [2, 2, 6, 2] # (list) number of Blocks in each stage 
window_size: 7 # (int) 
mlp_ratio: 4 # (int)
qkv_bias: True # (bool)
ape: True # (bool) absolute position embedding
use_pos_rel: True # (bool) relative position embedding
drop_out: 0.1 # (float) 
norm_eps: 1e-12 # (float) epsilon norm NormLayer


# Hyperparameter---------------------------------------------------------------------------------------------------------------------------
epochs: 10 # (int) number of epochs to train for
batch: 16 # (int) number of images per batch 
devices: cuda # (int ) device to run on, i.e. cuda  or device=cpu
pretrained: None # (bool | str) whether to use a pretrained model (bool) or a model to load weights from (str)
optimizer: Adam # (str) optimizer to use, choices=[SGD, Adam, Adamax, AdamW, NAdam, RAdam, RMSProp, auto]
weight_decay: 0.05
lr: 0.001
beta1: 0.9
beta2: 0.999
eps: 1e-8

# output
outputs_dir: ./outputs
logger: wandb

